CREATE TABLE "BOOT"."CRNA_PT_REG" 
   (	"CID" NUMBER NOT NULL ENABLE, 
	"PTNAME" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(20 BYTE), 
	"GENDER" VARCHAR2(20 BYTE), 
	"COUNTRY" VARCHAR2(20 BYTE), 
	"COUNTRY_CODE" NUMBER, 
	"MOBNO" VARCHAR2(20 BYTE), 
	 CONSTRAINT "CRNA_PT_REG_PK" PRIMARY KEY ("CID")